## container build, no sudo
sudo: false

language: cpp 

compiler: 
    - gcc 
    - clang

os:
    - linux

cache:
  apt:
  ccache:
  directories:

env:
    global:
        - GCC_VERSION=7
        - CXXFLAGS=-std=c++14
        - CFLAGS=-std=c99


branches:
    only:
        - master

before_install:
    -   if [ ${CC} != "clang" ]; then
            export CC=/usr/bin/gcc-${GCC_VERSION} CXX=/usr/bin/g++-${GCC_VERSION};
            C=gcc;
        fi


addons:
 apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
# ensure these match GCC_VERSION
      - gcc-7
      - g++-7
      - binutils
      - gawk
      - build-essential
      - wget
      - xz-utils
      - libtool
      - libnuma-dev
      - cmake

before_script:
    - echo $LANG
    - echo $LC_ALL
    - mkdir build
    - cd build
    - cmake ..



script:
    - ${CC} --version ; ${CXX} --version; cmake --version
    - env
    - make -j 4 && make test

