## container build, no sudo
sudo: false

language: cpp 

compiler: 
    - gcc 
    - clang

os:
    - linux

cache:
  apt:
  ccache:
  directories:
    - $HOME/binutils


env:
    global:
        - GCC_VERSION=5
        - CXXFLAGS=-std=c++11
        - CFLAGS=-std=c99

branches:
    only:
        - master

before_install:
    -   if [ ${CC} == "clang" ]; then
            export CC=/usr/bin/clang-3.7 CXX=/usr/bin/clang++-3.7;
            C=clang;
        else
            export CC=/usr/bin/gcc-${GCC_VERSION} CXX=/usr/bin/g++-${GCC_VERSION};
            C=gcc;
        fi


addons:
 apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-cmake-3.x
      - llvm-toolchain-precise
    packages:
# ensure these match GCC_VERSION
      - gcc-5
      - g++-5
      - clang-3.7
      - binutils
      - libgsl0-dev
      - libgsl0ldbl
      - gawk
      - cmake
      - build-essential
      - wget
      - libtool


before_script:
    - echo $LANG
    - echo $LC_ALL
    - mkdir build
    - cd build
    - cmake ..



script:
    - ${CC} --version ; ${CXX} --version
    - make && make test
