## container build, no sudo
sudo: false

language: cpp 

compiler: 
    - gcc 
    - clang

os:
    - linux

cache:
  apt:
  ccache:
  directories:
    - $HOME/cmake-3.4.0-Linux-x86_64

env:
    global:
        - GCC_VERSION=5
        - CMAKE_VERSION=3.4.0-Linux-x86_64
        - CXXFLAGS=-std=c++11
        - CFLAGS=-std=c99

branches:
    only:
        - master

before_install:
    -   if [ ${CC} == "clang" ]; then
            export CC=/usr/bin/clang-3.7 CXX=/usr/bin/clang++-3.7;
            C=clang;
        else
            export CC=/usr/bin/gcc-${GCC_VERSION} CXX=/usr/bin/g++-${GCC_VERSION};
            C=gcc;
        fi


addons:
 apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages:
# ensure these match GCC_VERSION
      - gcc-5
      - g++-5
      - clang-3.7
      - binutils
      - libgsl0-dev
      - libgsl0ldbl
      - gawk
      - build-essential
      - wget
      - libtool


before_script:
    - echo $LANG
    - echo $LC_ALL
    -   if [ ! -d "$HOME/cmake-3.4.0-Linux-x86_64/bin" ]; then
            wget --no-check-certificate https://cmake.org/files/v3.4/cmake-3.4.0-Linux-x86_64.tar.gz -O - | tar -zxf -;
        fi


    - mkdir build
    - cd build
    - $HOME/cmake-${CMAKE_VERSION}/bin/cmake ..



script:
    - ${CC} --version ; ${CXX} --version
    - make && make test
